#Name:Xuesen Cui
#Email:cuixuesen@ucla.edu
#ID:604941626
#NAME: Haiying Huang
#EMAIL: hhaiying1998@outlook.com
#ID: 804757410

default:build

build:
	gcc -g -Wall -Wextra -o lab3a lab3a.c

dist:
	tar -cvzf lab3a-804757410.tar.gz lab3a.c ext2_fs.h Makefile README

clean:
	rm -f lab3a lab3a-804757410.tar.gz
